# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fitcontrol.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fit_control_widget(object):
    def setupUi(self, fit_control_widget):
        fit_control_widget.setObjectName("fit_control_widget")
        fit_control_widget.resize(494, 767)
        self.verticalLayout = QtWidgets.QVBoxLayout(fit_control_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(fit_control_widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget1 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget1.setObjectName("tabWidget1")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.tabWidgetPage1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_4 = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(self.tabWidgetPage1)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fit_bar_progress = QtWidgets.QProgressBar(self.tabWidgetPage1)
        self.fit_bar_progress.setProperty("value", 24)
        self.fit_bar_progress.setObjectName("fit_bar_progress")
        self.horizontalLayout_4.addWidget(self.fit_bar_progress)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.fit_button_fit = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.fit_button_fit.setDefault(True)
        self.fit_button_fit.setObjectName("fit_button_fit")
        self.horizontalLayout_3.addWidget(self.fit_button_fit)
        self.pushButton_11 = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget1.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabWidgetPage2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget_2 = QtWidgets.QListWidget(self.tabWidgetPage2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_5.addWidget(self.listWidget_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_13 = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.pushButton_13.setDefault(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_5.addWidget(self.pushButton_13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget1.addTab(self.tabWidgetPage2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget1.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(fit_control_widget)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(fit_control_widget)

    def retranslateUi(self, fit_control_widget):
        _translate = QtCore.QCoreApplication.translate
        fit_control_widget.setWindowTitle(_translate("fit_control_widget", "Form"))
        self.groupBox.setTitle(_translate("fit_control_widget", "Data Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("fit_control_widget", "Data"))
        self.groupBox_2.setTitle(_translate("fit_control_widget", "Initialize Functions"))
        self.groupBox_3.setTitle(_translate("fit_control_widget", "Load fit from file"))
        self.groupBox_4.setTitle(_translate("fit_control_widget", "Fit range parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("fit_control_widget", "Set"))
        self.pushButton.setText(_translate("fit_control_widget", "<<"))
        self.pushButton_2.setText(_translate("fit_control_widget", "<"))
        self.label.setText(_translate("fit_control_widget", "TextLabel"))
        self.pushButton_4.setText(_translate("fit_control_widget", ">"))
        self.pushButton_5.setText(_translate("fit_control_widget", ">>"))
        self.pushButton_9.setText(_translate("fit_control_widget", "< Fit"))
        self.pushButton_10.setText(_translate("fit_control_widget", "< Copy"))
        self.fit_button_fit.setText(_translate("fit_control_widget", "Fit"))
        self.pushButton_11.setText(_translate("fit_control_widget", "Copy >"))
        self.pushButton_12.setText(_translate("fit_control_widget", "Fit >"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tabWidgetPage1), _translate("fit_control_widget", "Fit Functions"))
        self.pushButton_13.setText(_translate("fit_control_widget", "Set"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tabWidgetPage2), _translate("fit_control_widget", "Function Bounds"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab_4), _translate("fit_control_widget", "Edit Fit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("fit_control_widget", "Fit"))
        self.groupBox_5.setTitle(_translate("fit_control_widget", "Save Fit Files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("fit_control_widget", "Save"))

