# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_import.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_raw_import_window(object):
    def setupUi(self, raw_import_window):
        raw_import_window.setObjectName("raw_import_window")
        raw_import_window.setWindowModality(QtCore.Qt.NonModal)
        raw_import_window.resize(1059, 1185)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(raw_import_window.sizePolicy().hasHeightForWidth())
        raw_import_window.setSizePolicy(sizePolicy)
        raw_import_window.setMinimumSize(QtCore.QSize(0, 0))
        raw_import_window.setSizeIncrement(QtCore.QSize(1, 1))
        raw_import_window.setBaseSize(QtCore.QSize(600, 500))
        self.centralWidget = QtWidgets.QWidget(raw_import_window)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.raw_import_tab = QtWidgets.QTabWidget(self.centralWidget)
        self.raw_import_tab.setObjectName("raw_import_tab")
        self.files_tab = QtWidgets.QWidget()
        self.files_tab.setObjectName("files_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.files_tab)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.io_group_in = QtWidgets.QGroupBox(self.files_tab)
        self.io_group_in.setMinimumSize(QtCore.QSize(600, 230))
        self.io_group_in.setObjectName("io_group_in")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.io_group_in)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.io_layout_in = QtWidgets.QVBoxLayout()
        self.io_layout_in.setSpacing(6)
        self.io_layout_in.setObjectName("io_layout_in")
        self.io_label_in_header = QtWidgets.QLabel(self.io_group_in)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.io_label_in_header.sizePolicy().hasHeightForWidth())
        self.io_label_in_header.setSizePolicy(sizePolicy)
        self.io_label_in_header.setObjectName("io_label_in_header")
        self.io_layout_in.addWidget(self.io_label_in_header)
        self.io_label_in_body = QtWidgets.QLabel(self.io_group_in)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.io_label_in_body.sizePolicy().hasHeightForWidth())
        self.io_label_in_body.setSizePolicy(sizePolicy)
        self.io_label_in_body.setTextFormat(QtCore.Qt.PlainText)
        self.io_label_in_body.setWordWrap(True)
        self.io_label_in_body.setObjectName("io_label_in_body")
        self.io_layout_in.addWidget(self.io_label_in_body)
        self.io_in_horizontal_layout = QtWidgets.QHBoxLayout()
        self.io_in_horizontal_layout.setSpacing(6)
        self.io_in_horizontal_layout.setObjectName("io_in_horizontal_layout")
        self.io_input_in = QtWidgets.QLineEdit(self.io_group_in)
        self.io_input_in.setObjectName("io_input_in")
        self.io_in_horizontal_layout.addWidget(self.io_input_in)
        self.io_tool_select_in = QtWidgets.QToolButton(self.io_group_in)
        self.io_tool_select_in.setObjectName("io_tool_select_in")
        self.io_in_horizontal_layout.addWidget(self.io_tool_select_in)
        self.io_button_scan = QtWidgets.QPushButton(self.io_group_in)
        self.io_button_scan.setAutoDefault(False)
        self.io_button_scan.setDefault(False)
        self.io_button_scan.setObjectName("io_button_scan")
        self.io_in_horizontal_layout.addWidget(self.io_button_scan)
        self.io_layout_in.addLayout(self.io_in_horizontal_layout)
        self.verticalLayout_5.addLayout(self.io_layout_in)
        self.file_list_view = QtWidgets.QListView(self.io_group_in)
        self.file_list_view.setObjectName("file_list_view")
        self.verticalLayout_5.addWidget(self.file_list_view)
        self.verticalLayout_4.addWidget(self.io_group_in)
        self.type_group_identifier = QtWidgets.QGroupBox(self.files_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_group_identifier.sizePolicy().hasHeightForWidth())
        self.type_group_identifier.setSizePolicy(sizePolicy)
        self.type_group_identifier.setObjectName("type_group_identifier")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.type_group_identifier)
        self.verticalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.type_label_path = QtWidgets.QLabel(self.type_group_identifier)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_label_path.sizePolicy().hasHeightForWidth())
        self.type_label_path.setSizePolicy(sizePolicy)
        self.type_label_path.setMinimumSize(QtCore.QSize(0, 16))
        self.type_label_path.setText("None")
        self.type_label_path.setTextFormat(QtCore.Qt.RichText)
        self.type_label_path.setWordWrap(False)
        self.type_label_path.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.type_label_path.setObjectName("type_label_path")
        self.verticalLayout_15.addWidget(self.type_label_path)
        self.verticalLayout_4.addWidget(self.type_group_identifier)
        self.type_group_identified = QtWidgets.QGroupBox(self.files_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.type_group_identified.sizePolicy().hasHeightForWidth())
        self.type_group_identified.setSizePolicy(sizePolicy)
        self.type_group_identified.setMinimumSize(QtCore.QSize(0, 200))
        self.type_group_identified.setMaximumSize(QtCore.QSize(16777215, 350))
        self.type_group_identified.setObjectName("type_group_identified")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.type_group_identified)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.type_list_dimensions = QtWidgets.QListView(self.type_group_identified)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.type_list_dimensions.sizePolicy().hasHeightForWidth())
        self.type_list_dimensions.setSizePolicy(sizePolicy)
        self.type_list_dimensions.setObjectName("type_list_dimensions")
        self.horizontalLayout_3.addWidget(self.type_list_dimensions)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.type_label_name = QtWidgets.QLabel(self.type_group_identified)
        self.type_label_name.setObjectName("type_label_name")
        self.verticalLayout_2.addWidget(self.type_label_name)
        self.type_input_name = QtWidgets.QLineEdit(self.type_group_identified)
        self.type_input_name.setObjectName("type_input_name")
        self.verticalLayout_2.addWidget(self.type_input_name)
        self.type_label_unit = QtWidgets.QLabel(self.type_group_identified)
        self.type_label_unit.setObjectName("type_label_unit")
        self.verticalLayout_2.addWidget(self.type_label_unit)
        self.type_input_label = QtWidgets.QLineEdit(self.type_group_identified)
        self.type_input_label.setObjectName("type_input_label")
        self.verticalLayout_2.addWidget(self.type_input_label)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.type_button_set = QtWidgets.QPushButton(self.type_group_identified)
        self.type_button_set.setObjectName("type_button_set")
        self.horizontalLayout_10.addWidget(self.type_button_set)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.type_list_single_dimension = QtWidgets.QListView(self.type_group_identified)
        self.type_list_single_dimension.setObjectName("type_list_single_dimension")
        self.horizontalLayout_12.addWidget(self.type_list_single_dimension)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addWidget(self.type_group_identified)
        self.file_layout_nav = QtWidgets.QHBoxLayout()
        self.file_layout_nav.setSpacing(6)
        self.file_layout_nav.setObjectName("file_layout_nav")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.file_layout_nav.addItem(spacerItem2)
        self.file_button_reset = QtWidgets.QPushButton(self.files_tab)
        self.file_button_reset.setObjectName("file_button_reset")
        self.file_layout_nav.addWidget(self.file_button_reset)
        self.file_button_accept = QtWidgets.QPushButton(self.files_tab)
        self.file_button_accept.setDefault(True)
        self.file_button_accept.setFlat(False)
        self.file_button_accept.setObjectName("file_button_accept")
        self.file_layout_nav.addWidget(self.file_button_accept)
        self.verticalLayout_4.addLayout(self.file_layout_nav)
        self.raw_import_tab.addTab(self.files_tab, "")
        self.visual_tab = QtWidgets.QWidget()
        self.visual_tab.setObjectName("visual_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.visual_tab)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.visual_layout_selector = QtWidgets.QHBoxLayout()
        self.visual_layout_selector.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.visual_layout_selector.setSpacing(6)
        self.visual_layout_selector.setObjectName("visual_layout_selector")
        self.visual_label_selector = QtWidgets.QLabel(self.visual_tab)
        self.visual_label_selector.setObjectName("visual_label_selector")
        self.visual_layout_selector.addWidget(self.visual_label_selector)
        self.visual_combo_selector = QtWidgets.QComboBox(self.visual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_combo_selector.sizePolicy().hasHeightForWidth())
        self.visual_combo_selector.setSizePolicy(sizePolicy)
        self.visual_combo_selector.setMaxVisibleItems(20)
        self.visual_combo_selector.setDuplicatesEnabled(False)
        self.visual_combo_selector.setObjectName("visual_combo_selector")
        self.visual_layout_selector.addWidget(self.visual_combo_selector)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.visual_layout_selector.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.visual_layout_selector)
        self.visual_layout_plot = QtWidgets.QVBoxLayout()
        self.visual_layout_plot.setSpacing(6)
        self.visual_layout_plot.setObjectName("visual_layout_plot")
        self.visual_widget_plot = QtWidgets.QWidget(self.visual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_widget_plot.sizePolicy().hasHeightForWidth())
        self.visual_widget_plot.setSizePolicy(sizePolicy)
        self.visual_widget_plot.setObjectName("visual_widget_plot")
        self.visual_layout_plot.addWidget(self.visual_widget_plot)
        self.verticalLayout_3.addLayout(self.visual_layout_plot)
        self.visual_layout_nav = QtWidgets.QHBoxLayout()
        self.visual_layout_nav.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.visual_layout_nav.setSpacing(6)
        self.visual_layout_nav.setObjectName("visual_layout_nav")
        self.visual_label_x = QtWidgets.QLabel(self.visual_tab)
        self.visual_label_x.setObjectName("visual_label_x")
        self.visual_layout_nav.addWidget(self.visual_label_x)
        self.visual_input_x = QtWidgets.QLineEdit(self.visual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_input_x.sizePolicy().hasHeightForWidth())
        self.visual_input_x.setSizePolicy(sizePolicy)
        self.visual_input_x.setObjectName("visual_input_x")
        self.visual_layout_nav.addWidget(self.visual_input_x)
        self.lineEdit = QtWidgets.QLineEdit(self.visual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(2, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.visual_layout_nav.addWidget(self.lineEdit)
        self.visual_label_y = QtWidgets.QLabel(self.visual_tab)
        self.visual_label_y.setObjectName("visual_label_y")
        self.visual_layout_nav.addWidget(self.visual_label_y)
        self.visual_input_y = QtWidgets.QLineEdit(self.visual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visual_input_y.sizePolicy().hasHeightForWidth())
        self.visual_input_y.setSizePolicy(sizePolicy)
        self.visual_input_y.setObjectName("visual_input_y")
        self.visual_layout_nav.addWidget(self.visual_input_y)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.visual_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.visual_layout_nav.addWidget(self.lineEdit_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.visual_layout_nav.addItem(spacerItem4)
        self.visual_button_previous = QtWidgets.QPushButton(self.visual_tab)
        self.visual_button_previous.setObjectName("visual_button_previous")
        self.visual_layout_nav.addWidget(self.visual_button_previous)
        self.visual_button_next = QtWidgets.QPushButton(self.visual_tab)
        self.visual_button_next.setDefault(True)
        self.visual_button_next.setObjectName("visual_button_next")
        self.visual_layout_nav.addWidget(self.visual_button_next)
        self.verticalLayout_3.addLayout(self.visual_layout_nav)
        self.raw_import_tab.addTab(self.visual_tab, "")
        self.meta_tab = QtWidgets.QWidget()
        self.meta_tab.setObjectName("meta_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.meta_tab)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.meta_group_general = QtWidgets.QGroupBox(self.meta_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_group_general.sizePolicy().hasHeightForWidth())
        self.meta_group_general.setSizePolicy(sizePolicy)
        self.meta_group_general.setObjectName("meta_group_general")
        self.gridLayout = QtWidgets.QGridLayout(self.meta_group_general)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.meta_input_meas_date = QtWidgets.QLineEdit(self.meta_group_general)
        self.meta_input_meas_date.setObjectName("meta_input_meas_date")
        self.gridLayout.addWidget(self.meta_input_meas_date, 1, 1, 1, 1)
        self.meta_label_name = QtWidgets.QLabel(self.meta_group_general)
        self.meta_label_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_name.setObjectName("meta_label_name")
        self.gridLayout.addWidget(self.meta_label_name, 0, 0, 1, 1)
        self.meta_input_proc_date = QtWidgets.QLineEdit(self.meta_group_general)
        self.meta_input_proc_date.setObjectName("meta_input_proc_date")
        self.gridLayout.addWidget(self.meta_input_proc_date, 2, 1, 1, 1)
        self.meta_label_proc_date = QtWidgets.QLabel(self.meta_group_general)
        self.meta_label_proc_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_proc_date.setObjectName("meta_label_proc_date")
        self.gridLayout.addWidget(self.meta_label_proc_date, 2, 0, 1, 1)
        self.meta_input_name = QtWidgets.QLineEdit(self.meta_group_general)
        self.meta_input_name.setObjectName("meta_input_name")
        self.gridLayout.addWidget(self.meta_input_name, 0, 1, 1, 1)
        self.meta_label_meas_date = QtWidgets.QLabel(self.meta_group_general)
        self.meta_label_meas_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_meas_date.setObjectName("meta_label_meas_date")
        self.gridLayout.addWidget(self.meta_label_meas_date, 1, 0, 1, 1)
        self.horizontalLayout_14.addWidget(self.meta_group_general)
        self.meta_group_sample = QtWidgets.QGroupBox(self.meta_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_group_sample.sizePolicy().hasHeightForWidth())
        self.meta_group_sample.setSizePolicy(sizePolicy)
        self.meta_group_sample.setObjectName("meta_group_sample")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.meta_group_sample)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.meta_label_id = QtWidgets.QLabel(self.meta_group_sample)
        self.meta_label_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_id.setObjectName("meta_label_id")
        self.gridLayout_3.addWidget(self.meta_label_id, 0, 0, 1, 1)
        self.meta_input_id = QtWidgets.QLineEdit(self.meta_group_sample)
        self.meta_input_id.setObjectName("meta_input_id")
        self.gridLayout_3.addWidget(self.meta_input_id, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.meta_button_load_3 = QtWidgets.QPushButton(self.meta_group_sample)
        self.meta_button_load_3.setObjectName("meta_button_load_3")
        self.horizontalLayout_2.addWidget(self.meta_button_load_3)
        self.meta_button_vis = QtWidgets.QPushButton(self.meta_group_sample)
        self.meta_button_vis.setObjectName("meta_button_vis")
        self.horizontalLayout_2.addWidget(self.meta_button_vis)
        self.meta_button_load_2 = QtWidgets.QPushButton(self.meta_group_sample)
        self.meta_button_load_2.setObjectName("meta_button_load_2")
        self.horizontalLayout_2.addWidget(self.meta_button_load_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_14.addWidget(self.meta_group_sample)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.meta_group_instrument = QtWidgets.QGroupBox(self.meta_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_group_instrument.sizePolicy().hasHeightForWidth())
        self.meta_group_instrument.setSizePolicy(sizePolicy)
        self.meta_group_instrument.setObjectName("meta_group_instrument")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.meta_group_instrument)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.meta_input_aquisition = QtWidgets.QLineEdit(self.meta_group_instrument)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_aquisition.sizePolicy().hasHeightForWidth())
        self.meta_input_aquisition.setSizePolicy(sizePolicy)
        self.meta_input_aquisition.setObjectName("meta_input_aquisition")
        self.gridLayout_2.addWidget(self.meta_input_aquisition, 5, 1, 1, 1)
        self.meta_label_laser_unit = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_laser_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_laser_unit.setObjectName("meta_label_laser_unit")
        self.gridLayout_2.addWidget(self.meta_label_laser_unit, 0, 2, 1, 1)
        self.meta_label_gratting_unit = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_gratting_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_gratting_unit.setObjectName("meta_label_gratting_unit")
        self.gridLayout_2.addWidget(self.meta_label_gratting_unit, 2, 2, 1, 1)
        self.meta_label_aquisition = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_aquisition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_aquisition.setObjectName("meta_label_aquisition")
        self.gridLayout_2.addWidget(self.meta_label_aquisition, 5, 0, 1, 1)
        self.meta_input_gratting = QtWidgets.QLineEdit(self.meta_group_instrument)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_gratting.sizePolicy().hasHeightForWidth())
        self.meta_input_gratting.setSizePolicy(sizePolicy)
        self.meta_input_gratting.setObjectName("meta_input_gratting")
        self.gridLayout_2.addWidget(self.meta_input_gratting, 2, 1, 1, 1)
        self.meta_input_objective = QtWidgets.QLineEdit(self.meta_group_instrument)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_objective.sizePolicy().hasHeightForWidth())
        self.meta_input_objective.setSizePolicy(sizePolicy)
        self.meta_input_objective.setObjectName("meta_input_objective")
        self.gridLayout_2.addWidget(self.meta_input_objective, 3, 1, 1, 1)
        self.meta_label_objective_unit = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_objective_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_objective_unit.setObjectName("meta_label_objective_unit")
        self.gridLayout_2.addWidget(self.meta_label_objective_unit, 3, 2, 1, 1)
        self.meta_input_duration = QtWidgets.QLineEdit(self.meta_group_instrument)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_duration.sizePolicy().hasHeightForWidth())
        self.meta_input_duration.setSizePolicy(sizePolicy)
        self.meta_input_duration.setObjectName("meta_input_duration")
        self.gridLayout_2.addWidget(self.meta_input_duration, 4, 1, 1, 1)
        self.meta_label_laser = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_laser.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_laser.setObjectName("meta_label_laser")
        self.gridLayout_2.addWidget(self.meta_label_laser, 0, 0, 1, 1)
        self.meta_label_power = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_power.setObjectName("meta_label_power")
        self.gridLayout_2.addWidget(self.meta_label_power, 1, 0, 1, 1)
        self.meta_label_aquisition_unit = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_aquisition_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_aquisition_unit.setObjectName("meta_label_aquisition_unit")
        self.gridLayout_2.addWidget(self.meta_label_aquisition_unit, 5, 2, 1, 1)
        self.meta_label_gratting = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_gratting.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_gratting.setObjectName("meta_label_gratting")
        self.gridLayout_2.addWidget(self.meta_label_gratting, 2, 0, 1, 1)
        self.meta_label_duration = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_duration.setObjectName("meta_label_duration")
        self.gridLayout_2.addWidget(self.meta_label_duration, 4, 0, 1, 1)
        self.meta_label_power_unit = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_power_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_power_unit.setObjectName("meta_label_power_unit")
        self.gridLayout_2.addWidget(self.meta_label_power_unit, 1, 2, 1, 1)
        self.meta_input_laser = QtWidgets.QLineEdit(self.meta_group_instrument)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_laser.sizePolicy().hasHeightForWidth())
        self.meta_input_laser.setSizePolicy(sizePolicy)
        self.meta_input_laser.setObjectName("meta_input_laser")
        self.gridLayout_2.addWidget(self.meta_input_laser, 0, 1, 1, 1)
        self.meta_label_objective = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_objective.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_objective.setObjectName("meta_label_objective")
        self.gridLayout_2.addWidget(self.meta_label_objective, 3, 0, 1, 1)
        self.meta_input_power = QtWidgets.QLineEdit(self.meta_group_instrument)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_power.sizePolicy().hasHeightForWidth())
        self.meta_input_power.setSizePolicy(sizePolicy)
        self.meta_input_power.setObjectName("meta_input_power")
        self.gridLayout_2.addWidget(self.meta_input_power, 1, 1, 1, 1)
        self.meta_label_duration_unit = QtWidgets.QLabel(self.meta_group_instrument)
        self.meta_label_duration_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_duration_unit.setObjectName("meta_label_duration_unit")
        self.gridLayout_2.addWidget(self.meta_label_duration_unit, 4, 2, 1, 1)
        self.horizontalLayout_11.addWidget(self.meta_group_instrument)
        self.meta_group_parameters = QtWidgets.QGroupBox(self.meta_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_group_parameters.sizePolicy().hasHeightForWidth())
        self.meta_group_parameters.setSizePolicy(sizePolicy)
        self.meta_group_parameters.setObjectName("meta_group_parameters")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.meta_group_parameters)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.meta_label_orientation = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_orientation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_orientation.setObjectName("meta_label_orientation")
        self.gridLayout_5.addWidget(self.meta_label_orientation, 5, 0, 1, 1)
        self.meta_label_pressure = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_pressure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_pressure.setObjectName("meta_label_pressure")
        self.gridLayout_5.addWidget(self.meta_label_pressure, 1, 0, 1, 1)
        self.meta_input_orientation = QtWidgets.QLineEdit(self.meta_group_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_orientation.sizePolicy().hasHeightForWidth())
        self.meta_input_orientation.setSizePolicy(sizePolicy)
        self.meta_input_orientation.setObjectName("meta_input_orientation")
        self.gridLayout_5.addWidget(self.meta_input_orientation, 5, 1, 1, 1)
        self.meta_label_pressure_unit = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_pressure_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_pressure_unit.setObjectName("meta_label_pressure_unit")
        self.gridLayout_5.addWidget(self.meta_label_pressure_unit, 1, 2, 1, 1)
        self.meta_label_Intensity_unit = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_Intensity_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_Intensity_unit.setObjectName("meta_label_Intensity_unit")
        self.gridLayout_5.addWidget(self.meta_label_Intensity_unit, 4, 2, 1, 1)
        self.meta_input_pressure = QtWidgets.QLineEdit(self.meta_group_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_pressure.sizePolicy().hasHeightForWidth())
        self.meta_input_pressure.setSizePolicy(sizePolicy)
        self.meta_input_pressure.setObjectName("meta_input_pressure")
        self.gridLayout_5.addWidget(self.meta_input_pressure, 1, 1, 1, 1)
        self.meta_input_humidity = QtWidgets.QLineEdit(self.meta_group_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_humidity.sizePolicy().hasHeightForWidth())
        self.meta_input_humidity.setSizePolicy(sizePolicy)
        self.meta_input_humidity.setObjectName("meta_input_humidity")
        self.gridLayout_5.addWidget(self.meta_input_humidity, 2, 1, 1, 1)
        self.meta_label_orientation_unit = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_orientation_unit.setText("")
        self.meta_label_orientation_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_orientation_unit.setObjectName("meta_label_orientation_unit")
        self.gridLayout_5.addWidget(self.meta_label_orientation_unit, 5, 2, 1, 1)
        self.meta_input_intensity = QtWidgets.QLineEdit(self.meta_group_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_intensity.sizePolicy().hasHeightForWidth())
        self.meta_input_intensity.setSizePolicy(sizePolicy)
        self.meta_input_intensity.setObjectName("meta_input_intensity")
        self.gridLayout_5.addWidget(self.meta_input_intensity, 4, 1, 1, 1)
        self.meta_label_voltage = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_voltage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_voltage.setObjectName("meta_label_voltage")
        self.gridLayout_5.addWidget(self.meta_label_voltage, 3, 0, 1, 1)
        self.meta_input_temperature = QtWidgets.QLineEdit(self.meta_group_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_temperature.sizePolicy().hasHeightForWidth())
        self.meta_input_temperature.setSizePolicy(sizePolicy)
        self.meta_input_temperature.setObjectName("meta_input_temperature")
        self.gridLayout_5.addWidget(self.meta_input_temperature, 0, 1, 1, 1)
        self.meta_label_humidity = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_humidity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_humidity.setObjectName("meta_label_humidity")
        self.gridLayout_5.addWidget(self.meta_label_humidity, 2, 0, 1, 1)
        self.meta_label_voltage_unit = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_voltage_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_voltage_unit.setObjectName("meta_label_voltage_unit")
        self.gridLayout_5.addWidget(self.meta_label_voltage_unit, 3, 2, 1, 1)
        self.meta_label_Intensity = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_Intensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_Intensity.setObjectName("meta_label_Intensity")
        self.gridLayout_5.addWidget(self.meta_label_Intensity, 4, 0, 1, 1)
        self.meta_label_temp = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meta_label_temp.setObjectName("meta_label_temp")
        self.gridLayout_5.addWidget(self.meta_label_temp, 0, 0, 1, 1)
        self.meta_label_humidity_unit = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_humidity_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_humidity_unit.setObjectName("meta_label_humidity_unit")
        self.gridLayout_5.addWidget(self.meta_label_humidity_unit, 2, 2, 1, 1)
        self.meta_label_temp_unit = QtWidgets.QLabel(self.meta_group_parameters)
        self.meta_label_temp_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.meta_label_temp_unit.setObjectName("meta_label_temp_unit")
        self.gridLayout_5.addWidget(self.meta_label_temp_unit, 0, 2, 1, 1)
        self.meta_input_voltage = QtWidgets.QLineEdit(self.meta_group_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meta_input_voltage.sizePolicy().hasHeightForWidth())
        self.meta_input_voltage.setSizePolicy(sizePolicy)
        self.meta_input_voltage.setObjectName("meta_input_voltage")
        self.gridLayout_5.addWidget(self.meta_input_voltage, 3, 1, 1, 1)
        self.horizontalLayout_11.addWidget(self.meta_group_parameters)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.meta_label_comment = QtWidgets.QLabel(self.meta_tab)
        self.meta_label_comment.setObjectName("meta_label_comment")
        self.verticalLayout_9.addWidget(self.meta_label_comment)
        self.meta_text_comment = QtWidgets.QPlainTextEdit(self.meta_tab)
        self.meta_text_comment.setObjectName("meta_text_comment")
        self.verticalLayout_9.addWidget(self.meta_text_comment)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.meta_button_load = QtWidgets.QPushButton(self.meta_tab)
        self.meta_button_load.setObjectName("meta_button_load")
        self.horizontalLayout_8.addWidget(self.meta_button_load)
        self.meta_button_save = QtWidgets.QPushButton(self.meta_tab)
        self.meta_button_save.setObjectName("meta_button_save")
        self.horizontalLayout_8.addWidget(self.meta_button_save)
        spacerItem6 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.meta_button_previous = QtWidgets.QPushButton(self.meta_tab)
        self.meta_button_previous.setObjectName("meta_button_previous")
        self.horizontalLayout_8.addWidget(self.meta_button_previous)
        self.meta_button_accept = QtWidgets.QPushButton(self.meta_tab)
        self.meta_button_accept.setDefault(True)
        self.meta_button_accept.setObjectName("meta_button_accept")
        self.horizontalLayout_8.addWidget(self.meta_button_accept)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.raw_import_tab.addTab(self.meta_tab, "")
        self.dialog_tab = QtWidgets.QWidget()
        self.dialog_tab.setObjectName("dialog_tab")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.dialog_tab)
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.io_group_out = QtWidgets.QGroupBox(self.dialog_tab)
        self.io_group_out.setMinimumSize(QtCore.QSize(600, 150))
        self.io_group_out.setObjectName("io_group_out")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.io_group_out)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.io_layout_out = QtWidgets.QVBoxLayout()
        self.io_layout_out.setSpacing(6)
        self.io_layout_out.setObjectName("io_layout_out")
        self.io_label_out_header = QtWidgets.QLabel(self.io_group_out)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.io_label_out_header.sizePolicy().hasHeightForWidth())
        self.io_label_out_header.setSizePolicy(sizePolicy)
        self.io_label_out_header.setObjectName("io_label_out_header")
        self.io_layout_out.addWidget(self.io_label_out_header)
        self.io_label_out_body = QtWidgets.QLabel(self.io_group_out)
        self.io_label_out_body.setTextFormat(QtCore.Qt.PlainText)
        self.io_label_out_body.setWordWrap(True)
        self.io_label_out_body.setObjectName("io_label_out_body")
        self.io_layout_out.addWidget(self.io_label_out_body)
        self.io_out_horizontal_layout = QtWidgets.QHBoxLayout()
        self.io_out_horizontal_layout.setSpacing(6)
        self.io_out_horizontal_layout.setObjectName("io_out_horizontal_layout")
        self.io_input_out = QtWidgets.QLineEdit(self.io_group_out)
        self.io_input_out.setObjectName("io_input_out")
        self.io_out_horizontal_layout.addWidget(self.io_input_out)
        self.io_tool_select_out = QtWidgets.QToolButton(self.io_group_out)
        self.io_tool_select_out.setObjectName("io_tool_select_out")
        self.io_out_horizontal_layout.addWidget(self.io_tool_select_out)
        self.io_layout_out.addLayout(self.io_out_horizontal_layout)
        self.verticalLayout_8.addLayout(self.io_layout_out)
        self.verticalLayout_16.addWidget(self.io_group_out)
        self.dialog_textinput__text = QtWidgets.QTextBrowser(self.dialog_tab)
        self.dialog_textinput__text.setObjectName("dialog_textinput__text")
        self.verticalLayout_16.addWidget(self.dialog_textinput__text)
        self.dialog_layout_progress = QtWidgets.QHBoxLayout()
        self.dialog_layout_progress.setSpacing(6)
        self.dialog_layout_progress.setObjectName("dialog_layout_progress")
        self.dialog_progressbar_progressbar = QtWidgets.QProgressBar(self.dialog_tab)
        self.dialog_progressbar_progressbar.setProperty("value", 24)
        self.dialog_progressbar_progressbar.setObjectName("dialog_progressbar_progressbar")
        self.dialog_layout_progress.addWidget(self.dialog_progressbar_progressbar)
        self.dialog_label_progess = QtWidgets.QLabel(self.dialog_tab)
        self.dialog_label_progess.setObjectName("dialog_label_progess")
        self.dialog_layout_progress.addWidget(self.dialog_label_progess)
        self.verticalLayout_16.addLayout(self.dialog_layout_progress)
        self.dialog_layout_navigation = QtWidgets.QHBoxLayout()
        self.dialog_layout_navigation.setSpacing(6)
        self.dialog_layout_navigation.setObjectName("dialog_layout_navigation")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dialog_layout_navigation.addItem(spacerItem7)
        self.dialog_button_process = QtWidgets.QPushButton(self.dialog_tab)
        self.dialog_button_process.setObjectName("dialog_button_process")
        self.dialog_layout_navigation.addWidget(self.dialog_button_process)
        self.verticalLayout_16.addLayout(self.dialog_layout_navigation)
        self.raw_import_tab.addTab(self.dialog_tab, "")
        self.verticalLayout_14.addWidget(self.raw_import_tab)
        raw_import_window.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(raw_import_window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1059, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuConvert_dataset = QtWidgets.QMenu(self.menuBar)
        self.menuConvert_dataset.setObjectName("menuConvert_dataset")
        self.menuInfo = QtWidgets.QMenu(self.menuBar)
        self.menuInfo.setObjectName("menuInfo")
        self.menuAnalysis = QtWidgets.QMenu(self.menuBar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuData = QtWidgets.QMenu(self.menuBar)
        self.menuData.setObjectName("menuData")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        raw_import_window.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(raw_import_window)
        self.mainToolBar.setObjectName("mainToolBar")
        raw_import_window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(raw_import_window)
        self.statusBar.setObjectName("statusBar")
        raw_import_window.setStatusBar(self.statusBar)
        self.actionConvert_dataset = QtWidgets.QAction(raw_import_window)
        self.actionConvert_dataset.setObjectName("actionConvert_dataset")
        self.actionLoad_dataset = QtWidgets.QAction(raw_import_window)
        self.actionLoad_dataset.setObjectName("actionLoad_dataset")
        self.actionOpen_browser = QtWidgets.QAction(raw_import_window)
        self.actionOpen_browser.setObjectName("actionOpen_browser")
        self.actionSettings = QtWidgets.QAction(raw_import_window)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(raw_import_window)
        self.actionQuit.setObjectName("actionQuit")
        self.menuConvert_dataset.addAction(self.actionConvert_dataset)
        self.menuConvert_dataset.addSeparator()
        self.menuConvert_dataset.addAction(self.actionLoad_dataset)
        self.menuConvert_dataset.addAction(self.actionOpen_browser)
        self.menuConvert_dataset.addSeparator()
        self.menuConvert_dataset.addAction(self.actionSettings)
        self.menuConvert_dataset.addSeparator()
        self.menuConvert_dataset.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuConvert_dataset.menuAction())
        self.menuBar.addAction(self.menuInfo.menuAction())
        self.menuBar.addAction(self.menuAnalysis.menuAction())
        self.menuBar.addAction(self.menuData.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(raw_import_window)
        self.raw_import_tab.setCurrentIndex(0)
        self.visual_combo_selector.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(raw_import_window)

    def retranslateUi(self, raw_import_window):
        _translate = QtCore.QCoreApplication.translate
        raw_import_window.setWindowTitle(_translate("raw_import_window", "MainWindow"))
        self.io_group_in.setTitle(_translate("raw_import_window", "Input"))
        self.io_label_in_header.setText(_translate("raw_import_window", "Select the input Path:"))
        self.io_label_in_body.setText(_translate("raw_import_window", "This consist of telling the software in which folder the Raman spectra are located. Note that nothing else should be contained in this folder as it might result in an error when reading the information from the filename."))
        self.io_tool_select_in.setText(_translate("raw_import_window", "..."))
        self.io_button_scan.setText(_translate("raw_import_window", "Scan"))
        self.type_group_identifier.setTitle(_translate("raw_import_window", "Dimension identifier"))
        self.type_group_identified.setTitle(_translate("raw_import_window", "Identified the dimensions"))
        self.type_label_name.setText(_translate("raw_import_window", "Name"))
        self.type_label_unit.setText(_translate("raw_import_window", "Unit"))
        self.type_button_set.setText(_translate("raw_import_window", "Set"))
        self.file_button_reset.setText(_translate("raw_import_window", "Reset"))
        self.file_button_accept.setText(_translate("raw_import_window", "Accept"))
        self.raw_import_tab.setTabText(self.raw_import_tab.indexOf(self.files_tab), _translate("raw_import_window", "Files"))
        self.visual_label_selector.setText(_translate("raw_import_window", "Select a file: "))
        self.visual_label_x.setText(_translate("raw_import_window", "X Axis"))
        self.visual_input_x.setText(_translate("raw_import_window", "Wavenumber"))
        self.lineEdit.setText(_translate("raw_import_window", "cm-1"))
        self.visual_label_y.setText(_translate("raw_import_window", "Y Axis"))
        self.visual_input_y.setText(_translate("raw_import_window", "Intensity"))
        self.lineEdit_2.setText(_translate("raw_import_window", "a.u."))
        self.visual_button_previous.setText(_translate("raw_import_window", "Previous"))
        self.visual_button_next.setText(_translate("raw_import_window", "Next"))
        self.raw_import_tab.setTabText(self.raw_import_tab.indexOf(self.visual_tab), _translate("raw_import_window", "Visual"))
        self.meta_group_general.setTitle(_translate("raw_import_window", "General information"))
        self.meta_label_name.setText(_translate("raw_import_window", "Measurement Name"))
        self.meta_label_proc_date.setText(_translate("raw_import_window", "Processing Time"))
        self.meta_input_name.setText(_translate("raw_import_window", "No Name"))
        self.meta_label_meas_date.setText(_translate("raw_import_window", "Measurment Date"))
        self.meta_group_sample.setTitle(_translate("raw_import_window", "Sample information"))
        self.meta_label_id.setText(_translate("raw_import_window", "Sample ID"))
        self.meta_input_id.setText(_translate("raw_import_window", "No Name"))
        self.meta_button_load_3.setText(_translate("raw_import_window", "Remove"))
        self.meta_button_vis.setText(_translate("raw_import_window", "Visualize"))
        self.meta_button_load_2.setText(_translate("raw_import_window", "Load"))
        self.meta_group_instrument.setTitle(_translate("raw_import_window", "Instrument state"))
        self.meta_input_aquisition.setText(_translate("raw_import_window", "30"))
        self.meta_label_laser_unit.setText(_translate("raw_import_window", "nm"))
        self.meta_label_gratting_unit.setText(_translate("raw_import_window", "cm-1"))
        self.meta_label_aquisition.setText(_translate("raw_import_window", "n° aqui."))
        self.meta_input_gratting.setText(_translate("raw_import_window", "2400"))
        self.meta_input_objective.setText(_translate("raw_import_window", "100"))
        self.meta_label_objective_unit.setText(_translate("raw_import_window", "x"))
        self.meta_input_duration.setText(_translate("raw_import_window", "60"))
        self.meta_label_laser.setText(_translate("raw_import_window", "Laser"))
        self.meta_label_power.setText(_translate("raw_import_window", "Power"))
        self.meta_label_aquisition_unit.setText(_translate("raw_import_window", "x"))
        self.meta_label_gratting.setText(_translate("raw_import_window", "Gratting"))
        self.meta_label_duration.setText(_translate("raw_import_window", "Duration"))
        self.meta_label_power_unit.setText(_translate("raw_import_window", "%"))
        self.meta_input_laser.setText(_translate("raw_import_window", "633"))
        self.meta_label_objective.setText(_translate("raw_import_window", "Objective"))
        self.meta_input_power.setText(_translate("raw_import_window", "10"))
        self.meta_label_duration_unit.setText(_translate("raw_import_window", "s"))
        self.meta_group_parameters.setTitle(_translate("raw_import_window", "Measurement parameters"))
        self.meta_label_orientation.setText(_translate("raw_import_window", "Orientation"))
        self.meta_label_pressure.setText(_translate("raw_import_window", "Pressure"))
        self.meta_input_orientation.setText(_translate("raw_import_window", "001"))
        self.meta_label_pressure_unit.setText(_translate("raw_import_window", "bar"))
        self.meta_label_Intensity_unit.setText(_translate("raw_import_window", "I"))
        self.meta_input_pressure.setText(_translate("raw_import_window", "1"))
        self.meta_input_humidity.setText(_translate("raw_import_window", "0"))
        self.meta_input_intensity.setText(_translate("raw_import_window", "0"))
        self.meta_label_voltage.setText(_translate("raw_import_window", "Voltage"))
        self.meta_input_temperature.setText(_translate("raw_import_window", "297"))
        self.meta_label_humidity.setText(_translate("raw_import_window", "Humidity"))
        self.meta_label_voltage_unit.setText(_translate("raw_import_window", "V"))
        self.meta_label_Intensity.setText(_translate("raw_import_window", "Intensity"))
        self.meta_label_temp.setText(_translate("raw_import_window", "Temperature"))
        self.meta_label_humidity_unit.setText(_translate("raw_import_window", "%"))
        self.meta_label_temp_unit.setText(_translate("raw_import_window", "K"))
        self.meta_input_voltage.setText(_translate("raw_import_window", "0"))
        self.meta_label_comment.setText(_translate("raw_import_window", "Comments"))
        self.meta_button_load.setText(_translate("raw_import_window", "Load"))
        self.meta_button_save.setText(_translate("raw_import_window", "Save"))
        self.meta_button_previous.setText(_translate("raw_import_window", "Previous"))
        self.meta_button_accept.setText(_translate("raw_import_window", "Accept"))
        self.raw_import_tab.setTabText(self.raw_import_tab.indexOf(self.meta_tab), _translate("raw_import_window", "Measurement"))
        self.io_group_out.setTitle(_translate("raw_import_window", "Output"))
        self.io_label_out_header.setText(_translate("raw_import_window", "Select the output Path:"))
        self.io_label_out_body.setText(_translate("raw_import_window", "This is the folder in which the resulting single file processed Raman signal will be stored. If no Path is selected the folder of the input path will be used."))
        self.io_tool_select_out.setText(_translate("raw_import_window", "..."))
        self.dialog_label_progess.setText(_translate("raw_import_window", "TextLabel"))
        self.dialog_button_process.setText(_translate("raw_import_window", "Process"))
        self.raw_import_tab.setTabText(self.raw_import_tab.indexOf(self.dialog_tab), _translate("raw_import_window", "Dialog"))
        self.menuConvert_dataset.setTitle(_translate("raw_import_window", "File"))
        self.menuInfo.setTitle(_translate("raw_import_window", "Info"))
        self.menuAnalysis.setTitle(_translate("raw_import_window", "Analysis"))
        self.menuData.setTitle(_translate("raw_import_window", "Data"))
        self.menuHelp.setTitle(_translate("raw_import_window", "Help"))
        self.actionConvert_dataset.setText(_translate("raw_import_window", "Convert dataset"))
        self.actionLoad_dataset.setText(_translate("raw_import_window", "Open datatset"))
        self.actionOpen_browser.setText(_translate("raw_import_window", "Open browser"))
        self.actionSettings.setText(_translate("raw_import_window", "Settings"))
        self.actionQuit.setText(_translate("raw_import_window", "Quit"))

